### ISSUE TITLE
A minor improvement

### ISSUE THREAD

**Issue by natewind** [PrivOci/ReTube#1]
I’m too lazy to clone and create a pull request just for this, but [util.py#L28-L32](https://github.com/PrivOci/ReTube/blob/main/backend/utils/util.py#L28-L32) could be simpler and flatter:

```py
from itertools import count

part_to_seconds = lambda part, order: int(part) * pow(60, order)
return sum(map(part_to_seconds, reversed(time_parts), count())
```

Or, at the very least, [util.py#L31](https://github.com/PrivOci/ReTube/blob/main/backend/utils/util.py#L31) should be just:

```py
sum += part * pow(60, count)
```

x⁰ = 1, and Python knows this.

**Comment by natewind** [comment]
Also, [lbry.py#L58-L61](https://github.com/PrivOci/ReTube/blob/main/backend/extract_details/lbry.py#L58-L61) could be more direct:

```py
return data["result"]["streaming_url"] if "result" in data else None
```

**Comment by PrivOci** [comment]
Thanks Nate
